# Generated by Django 2.2.3 on 2020-05-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='来蛋时间')),
                ('batch', models.IntegerField(verbose_name='批次')),
                ('customer', models.CharField(max_length=255, verbose_name='来蛋客户')),
                ('incubator', models.IntegerField(verbose_name='孵化机')),
                ('hatch_pattern', models.SmallIntegerField(choices=[(1, '冬温大蛋'), (2, '冬温小蛋'), (3, '夏温大蛋'), (4, '夏温小蛋')], default=3, verbose_name='有效期限单位')),
                ('out_machine', models.IntegerField(verbose_name='出壳机')),
                ('begin_time', models.DateTimeField(verbose_name='够温时间')),
                ('end_time', models.DateTimeField(verbose_name='出苗时间')),
            ],
        ),
        migrations.CreateModel(
            name='HatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varieties', models.CharField(max_length=32, verbose_name='品种')),
                ('number_cases', models.IntegerField(verbose_name='件数')),
                ('all_number', models.IntegerField(verbose_name='装机蛋数')),
                ('break_eggs', models.IntegerField(blank=True, null=True, verbose_name='次破总数')),
                ('dead_eggs', models.IntegerField(blank=True, null=True, verbose_name='无精总数')),
                ('live_eggs', models.IntegerField(blank=True, null=True, verbose_name='活精总数')),
                ('fertilization_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='受精率')),
                ('m_miao', models.IntegerField(blank=True, null=True, verbose_name='公苗')),
                ('f_miao', models.IntegerField(blank=True, null=True, verbose_name='母苗')),
                ('fix_miao', models.IntegerField(blank=True, null=True, verbose_name='混合苗')),
                ('all_miao', models.IntegerField(blank=True, null=True, verbose_name='总苗数')),
                ('shoujing_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='受精率')),
                ('zongdan_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='受精率')),
                ('hatchrecord', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tabulation.HatchRecord', verbose_name='孵化基础信息')),
            ],
        ),
    ]
