# Generated by Django 2.2.3 on 2020-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabulation', '0003_auto_20200519_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatchrecord',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='够温时间'),
        ),
        migrations.AlterField(
            model_name='hatchrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出苗时间'),
        ),
    ]
